"""This program calculates the percentage of GC in a given DNA  sequence of Lac I gene"""

dna_seq = """ATGACCATGATTACGGATTCACTGGCCGTCGTTTTACAACGTCGTGACTGG
GCCGCACTGGCCGTCGTTTTACAACGTCGTGACTGGGAAAACCCTGGCGTTACCCAACTTAATC
GCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCC
TTCCCAACAGTTGCGCAGCCTGAATGGCGAATGGCGCTTTGCCTGGTTTCCGGCACCAGAAGCG
GTGCCGGAACTGACGCTGCCGCAAGCACTGACCCGGAACTGAAAGCGTCTGGCCTTCTCGCCTT
CTTGACGAGTTCTTCTGAGCGGGACTCTGGGGTTCGAAATGACCAGCGAATACCTGTTCCAGAA
CATTGCCAGTCAGTTGCTCAATGTACCTATAACCAGACCGTTCAGCTGGATATTACGGCCTTTT
AACTTCTCAGGCGTTCTCGGGGACTGAGAGTGCGGCTGGCTGGCATAAATATCTCAAGGTTACC
TGACCGCTTGCTGCAACTCTCTCAGGGCCAGGCGGTGACCGTCTCCGGCCAGATGAAGGCCAGT
AAGCAGGGGCAAGGTTGGAACAGGTATTCGCCGCCTACTGCAAGGCGGAATGTTGCGTGTCTCC
TTTGAAGCCGATCTTCCAGACGCGGATGAAGGCACCGGATGTGAATGCTGTTCCCGCTGCCGCT
GCCGGGTGCGCCTCTTACACATCTGGCGAAAGGGGGATGTGCTGCAAGGCGATTAAGTTGGGTA
ACGCCAGGGTTTTCCCAGTCACGACGTTGTAAAACGACGGCCAGTGAA"""

#DNA sequence of the Lac I gene
DNA_seq = dna_seq.upper()
#converts the input dna sequence into uppercase
no_c = DNA_seq.count('C')
#to count the repetition of C in dna
no_g = DNA_seq.count('G')
#to count the repition of G in dna
dna_length = len(DNA_seq)
#to count the total length of dna sequence in Lac I gene
gc_percent = (no_c + no_g)/dna_length*100.0
#calculates the gc content
print(f"The GC percent is: {gc_percent:.2f}%")

if gc_percent > 50:
    print("Since the Lac I gene has more GC content, it is GC rich")
    
else:
    print("Since the Lac I gene has more AT content, it is AT rich")
    #to check whether the dna sequence of Lac I gene is AT or GC rich